{% set name = "distarray" %}
{% set version = "2.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/distarray/archive/2.12.1.tar.gz
  sha256: 970598feab420ff4d0b75f289ec8693b8ad2436ad60fa246317a51732cdf6f00

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - future
  run:
    - python
    - future
test:
    imports:
     - distarray

about:
  home: http://uvcdat.llnl.gov/
  license: BSD 3-Clause
  license_file: 'license.txt'
  summary: 'Big Array partitionned in sub arrays'
  description: |
      Divide work among proceses for ensemble runs, linear interpolation,
      finity differencign.  Leverage the cores on the computer and is MPI ready.
  dev_url: https://github.com/UV-CDAT/distarray

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
