{% set name = "distarray" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/distarray/archive/2.12.2.tar.gz
  sha256: ca6ee7610b8e8309cec47121b2454d8d318bfe37b6db3b950c65b1316035ba6c

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - future
  run:
    - python
    - future
test:
    imports:
     - distarray

about:
  home: http://uvcdat.llnl.gov/
  license: BSD 3-Clause
  license_file: 'license.txt'
  summary: 'Big Array partitionned in sub arrays'
  description: |
      Divide work among proceses for ensemble runs, linear interpolation,
      finity differencign.  Leverage the cores on the computer and is MPI ready.
  dev_url: https://github.com/UV-CDAT/distarray

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
