travis:
  secure:
    BINSTAR_TOKEN: mbNwLdb4sboZQLRDj6CijTm9dtCQ7zWXu5DIcj8WIURJIAsDIa9nu97qN7w2DqHvyQ0zYGd0w2v11FP7ckv64f9uYl+PZ1YsZaOTiA19H12q9WphlDR3or4oYZSTaRcU0uhFeiiizbImaEZoxRvD3pT9eWXzeRahWNT+B3hNiHH0Ker5GmfeM6GN4Cibcj0wbb3vvlK5AA/CJ7ltaBYpX1/BOtH/NK152XAts156cZYZwyozZrUqoeUyg0dDZgia88RwV9DuWcY976macoiHyFbOqJ7bVnOmWh92mxTa18jmZLwmGU/KOUrYQMxESXmUWvNgP5AQB19qHpMMtIb3b6+UsP3ZqU4unAXVm6DsTuaudmrtEOHqPY0Mtx6TkDC5ma5rcaL0cAZcJ55/jIltS7kxqhC57hELjpMDP8U9WkB4iXbqdHGLbQ8kDMUott3N9hO551AN0wlv/tfwyKPQ6QG6xPW3yTPJyPJbr55gYJ7Pufy6ifeT7uFgtZ4EVd9/wcA0E6Cqz7yYWmSwgaeVFKXP88cUiHhAu2NyEGHAXuu5Gt4OUngTsK6rCDIvypRLf/cX2lbLzNUJLLQ4OsBXIfnPayqs65jZPPDIngfGppH6orRJ5sH2N7wXtG/E+I69GLTREbor0Rt5hJW7Rso7PF7+lfKHUZkjHYXguupgMxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
