appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BxrItxZZ1WOA0uvD3lZV9YNVtyTisKPTyYsfYpV4HxWdaiUpvOC/uvjwEMpF0ZAOZ3pa+xKlrdolqcXqR0EMkiWMP1lxnob544ufMUV9dmrvAsUcC34p81x6Xvfh/lidvJfOeUbTMpCOoHMyQYtkjyzTjtbwCjcC8qOpqZaj0QCUXeP0UlSc/R1bB+8lUmIC6RG/jjk/WUNKnk5+AUxKd88oA8ipUKuit4YfFZNMavasWE+eHG9FG0HIyByxSB9ZnecowV/gemb9SKGsnynP9PxJPje/2vhSKYz5dEMQAEDn6XeCxA/k/1vQwWRiIC8/lsXol/iX9+xVekODRZqgB8gM0ejsc/+3PnwjlxVdT+dUkjpFWSqfMwxpB4B1lJqzXJRPY+Sk28R/+HbWvjAH+Mwba2Yarb2Hhn0f1uj0VMt/Y5JoD5ynPPhRkhRUb/ZAjOB4fYIDcRXBehmOZiJhbL2hNWXH54gRB2Z44nigc7yBBpIPSc217tn9Ygu+4AqlDDp3+NohDfImYU0tXjKcY8/WyZzDfweX/MFNfJ+nV/fCoc1ubzhV0MIgidNyNJdPfn6FcylfVZGIa1IF2eAXwiUmDB90dOpIcMLwJHlzuO/uRLwe2AGYpXvR1/QKVuKMwxw9wLXV4BiGqlroV8CJnUzR2pkdrkHXfCCfOeo/TxY=}
conda_forge_output_validation: true
